UPDATE SECPDTA.SEC_GRP
SET LOCATION = REPLACE(LOCATION, 'screenid=MasterData', 'screenid=MasterJSData')
WHERE MENU_NAME = 'DAMAGE_TYPE';

UPDATE SECPDTA.B2B_CDTY
SET KEY_COLUMNS = LOWER(KEY_COLUMNS)
WHERE CODE_TYPE = 'DMG_TYP';

UPDATE SECPDTA.B2B_MTDT
SET FIELD = LOWER(FIELD),
LOV_FILTER_COLUMN = LOWER(LOV_FILTER_COLUMN),
LOV_RETURN_COLUMN = LOWER(LOV_RETURN_COLUMN)
WHERE CODE_TYPE = 'DMG_TYP';
